[LIBCLOUD-905] Added list images method for OnApp
apache/libcloud pull request #1011
Opened 2017-03-16 23:07 UTC by hackedunit

## Added list images method for OnApp

### Description
- Implements methods for listing available images for OnApp driver
- Includes tests and documentation

JIRA ticket: https://issues.apache.org/jira/browse/LIBCLOUD-905
Provider API doc: https://docs.onapp.com/display/52API/Get+List+of+All+Templates

### Status

- done, ready for review

### Checklist (tick everything that applies)

- [x] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide)
- [x] Documentation
- [x] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes)

2017-04-01 03:21 UTC, tonybaloney requested changes
changes LGTM, just 1 small comment left behind before it can be merged. thanks

2017-04-01 03:21 UTC, tonybaloney commented on libcloud/compute/drivers/onapp.py
> +        # return list(map(self._to_image, data['image_template']))
please remove this commented line

2017-04-01 22:41 UTC, tonybaloney commented
👍

2017-04-01 22:43 UTC, closed without merging

2017-04-04 13:25 UTC, hackedunit commented
@tonybaloney quick question - do I still need to attach a patch to the issue at JIRA as explained in the dev guide? Looks like these changes are already in trunk.