Add i3 instance types for AWS
apache/libcloud pull request #1038
Opened 2017-04-21 18:29 UTC by smullins7

Followed the r4 commit, adding i3 instances types for AWS. First time caller so let me know if I missed anything, please and thank you!

2017-04-21 22:17 UTC, tonybaloney requested changes
thank you for your first contribution! all looks ok except the tests are failing because the number of sizes is now wrong. run `tox -e py2.7` for example to run the test suite locally making sure it passes first or `python -m libcloud.test.compute.test_ec2` to just run the ec2 module

2017-04-21 22:17 UTC, tonybaloney commented on libcloud/test/compute/test_ec2.py
> +                self.assertEqual(len(sizes), 56)
it's now 58, according to the tests.

2017-04-24 13:40 UTC, smullins7 commented on libcloud/test/compute/test_ec2.py
> +                self.assertEqual(len(sizes), 56)
Cool thank you! I fixed it and a couple more and just pushed. Fyi I had to copy the secrets file to get it to import. I'm not sure if there are setup steps I'm supposed to follow but I just did the following:
`cp libcloud/test/secrets.py-dist libcloud/test/secrets.py`

2017-04-24 17:35 UTC, smullins7 commented
@tonybaloney looks like the tests pass, if this gets pulled in do you know when the next RC version would be released?

2017-05-02 05:13 UTC, tonybaloney commented
👍  this will go into 2.0.1

2017-05-02 05:15 UTC, closed without merging