Implement get_image function for softlayer
apache/libcloud pull request #1066
Opened 2017-05-30 16:37 UTC by IVBakker

## Implement get_image function for softlayer

### Description

`libcloud/libcloud/compute/base.py`propose a function `get_image` which isn't implement in softlayer.

### Status

- done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [o ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2017-06-22 03:16 UTC, tonybaloney requested changes

2017-06-22 03:16 UTC, tonybaloney commented on libcloud/compute/drivers/softlayer.py
> +            raise LibcloudError('could not find the image with id %s' % image_id)
this line is slightly too long and failing the linter

2017-06-22 03:17 UTC, tonybaloney commented
thanks for your contribution @IVBakker can you please add a complimentary test

2017-06-26 10:46 UTC, IVBakker commented
I'll make the linter happier and look for a test coverage.

2017-08-03 12:46 UTC, IVBakker commented
@tonybaloney The CI build is failing on:
```
 File "../contrib/generate_provider_feature_matrix_table.py", line 312, in generate_providers_table
    base_method = base_methods[method_name]
KeyError: 'create_balancer'
ERROR: InvocationError: '/home/travis/build/apache/libcloud/.tox/docs-travis/bin/python ../contrib/generate_provider_feature_matrix_table.py'
```
I don't think this is related to my change.

2017-08-11 04:33 UTC, tonybaloney commented
:+1: thanks @IVBakker no the CI failure is unrelated.

2017-08-11 04:35 UTC, closed without merging