BUGFIX GCE: Allow the setting of service account in instance templates
apache/libcloud pull request #1108
Opened 2017-09-08 13:06 UTC by evancarter-iex

## BUGFIX: GCE Allow the setting of service account in instance templates and instance properties

### Description
Currently, there is no way for the service account for an instance template to be set, despite that information being passed in. This fixes that problem.

### Status

Done, ready for review

### Checklist (tick everything that applies)

- [X ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [X ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)

2017-09-09 11:07 UTC, pquentin commented
Makes sense from the outside.

So you check "tests" but that is about automated tests, not manual verification that the fix works.

2017-09-11 12:16 UTC, evancarter-iex commented
Removed the tests section.

2017-09-20 07:17 UTC, pquentin commented
@evancarter-iex Not sure what you removed, what I'm saying is that this needs an automated test. Thanks.

2017-09-28 13:26 UTC, evancarter-iex commented
Any update on getting this checked in?

2017-09-28 13:36 UTC, pquentin commented
@evancarter-iex As said before, you need to add automated tests before this can get checked in. Otherwise this feature can break easily in the future.

2017-09-28 14:07 UTC, evancarter-iex commented
@pquentin I added some tests but I am not that familiar with how you have your stuff setup.

2017-09-28 14:46 UTC, psachin commented on libcloud/test/compute/test_gce.py
> +        self.assertTrue('scopes' in actual)
Should add one more assert to verify email
```
self.assertEqual(actual['email'], 'test@test.com')
```

2017-09-28 14:50 UTC, evancarter-iex commented
Added

2017-09-28 15:01 UTC, psachin requested changes

2017-09-28 15:01 UTC, psachin commented on libcloud/test/compute/test_gce.py
> +        self.assertTrue('scopes' in actual)
I think after adding the `else` part you should check both 'default' and user provided email. Something like,
```
input = {'scopes': ['compute-ro']}
actual = self.driver._build_service_account_with_email_gce_struct(input) 
self.assertTrue('email' in actual)
self.assertEqual(actual['email'], 'default')
self.assertTrue('scopes' in actual)

input = {'scopes': ['compute-ro'], 'email': 'test@test.com'}
actual = self.driver._build_service_account_with_email_gce_struct(input) 
self.assertTrue('email' in actual)
self.assertEqual(actual['email'], 'test@test.com')
self.assertTrue('scopes' in actual)
```

2017-09-28 15:01 UTC, psachin commented on libcloud/test/compute/test_gce.py
> +        self.assertTrue('scopes' in actual)
Are your tests passing locally?

2017-09-28 16:57 UTC, evancarter-iex commented
@psachin fixed the tests. Sorry about that

2017-09-28 17:39 UTC, pquentin commented
@psachin If you can review the code and say whether you approve the pull request or request changes, it will get this merged faster. Thanks!

2017-09-29 05:28 UTC, closed without merging

2017-09-29 05:29 UTC, pquentin commented
@evancarter-iex @psachin Thanks, this has been merged in trunk! ✨