packet.net optimizations
apache/libcloud pull request #987
Opened 2017-02-15 16:30 UTC by mgogoulos

## packet.net optimizations

### Description

- Use multiprocessing to get nodes without specifying project_id
Function list_nodes can also receive a project_id and return node on this
project, but if called without one it will fetch nodes on all projects

- fix list_sizes to return only server sizes (now it contains other items, as storage)
- provide cloud_init on create_node
- add functions ex_start_node and ex_stop_node
- add extra metadata on list_nodes
- add Project object with information for the Project
- add ex_list_projects function

### Status

done, ready for review

### Checklist (tick everything that applies)

- [ ] [Code linting](http://libcloud.readthedocs.org/en/latest/development.html#code-style-guide) (required, can be done after the PR checks)
- [ ] Documentation
- [ ] [Tests](http://libcloud.readthedocs.org/en/latest/testing.html)
- [ ] [ICLA](http://libcloud.readthedocs.org/en/latest/development.html#contributing-bigger-changes) (required for bigger changes)

2017-02-15 16:35 UTC, mgogoulos commented
I understand that introducing multiprocessing is a big change for libcloud, however it is a no go if you want list_nodes to return soon and have a big number of projects. This has worked without problems for us on mist.io for Azure, vCloud and packet.net . Happy to provide more info

2017-04-01 00:50 UTC, tonybaloney commented
hey @mgogoulos I was considering having an aiohttp pattern and using async/await for certain methods instead of introducing a non-standard threading library.
let's discuss on the dev channel

2017-06-10 11:23 UTC, PastelStorm requested changes
I ran a Pylint check on your PR and made a review. Please have a look. Thanks.

2017-06-10 11:23 UTC, alrick87 commented on libcloud/compute/drivers/packet.py
> +from libcloud.compute.providers import Provider, get_driver
Reimport 'Provider' (imported line 23)

2017-06-10 11:23 UTC, alrick87 commented on libcloud/compute/drivers/packet.py
> +                    except:
No exception type(s) specified

2017-06-10 11:23 UTC, alrick87 commented on libcloud/compute/drivers/packet.py
> +            data = self.connection.request('/projects/%s/devices' %
Bad indentation. Found 12 spaces, expected 8

2017-06-10 11:23 UTC, alrick87 commented on libcloud/compute/drivers/packet.py
> +            return list(map(self._to_node, data))
Bad indentation. Found 12 spaces, expected 8

2017-06-10 11:23 UTC, alrick87 commented on libcloud/compute/drivers/packet.py
> +                                           ).object['devices']
Wrong continued indentation (remove 1 space)

2017-06-10 11:23 UTC, alrick87 commented on libcloud/compute/drivers/packet.py
> +        cpus = data['specs']['cpus'][0].get('count')
Unused variable 'cpus'

2019-07-16 17:39 UTC, Kami commented
Superseded by #1282 so I'm closing this PR.

2019-07-16 17:39 UTC, closed without merging